# Generated by Django 4.0 on 2021-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opioids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'credential',
            },
        ),
    ]
