# Generated by Django 3.2.8 on 2021-12-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Opioids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriber',
            name='state',
        ),
    ]
