# Generated by Django 4.0 on 2021-12-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opioids', '0002_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentialz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentialz', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'credentialz',
            },
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
